- name: Gather all VMs from a specific folder
  community.vmware.vmware_vm_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: False
    folder: "/{{ datacenter_name }}/vm/Sys-intern/"
  delegate_to: localhost
  register: vm_info

- debug:
    var: vm_info.virtual_machines

- name: Create Snapshot
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    datacenter: "{{ datacenter_name }}"
    name: "{{ item.guest_name }}"
    folder: "/{{ datacenter_name }}/vm/Sys-intern/"
    snapshot_name: "{{ snapshot_name }}"
    state: present
  loop: "{{ vm_info.virtual_machines }}"
  #  loop_control:
  #    loop_var: item
  #  when: item.resource_pool_name == resource_pool_name
  #  delegate_to: localhost
